### ISSUE TITLE
another dictionary

### ISSUE THREAD

**Issue by ghost** [d0b3rm4n/harbour-sidudict#4]
can you add this dictionary to the list? https://github.com/norayr/freearmdicto

**Comment by d0b3rm4n** [comment]
The source of the files look rather suspicious to me, it seems the copyright of this dictionary belongs to a company called "Troy Software opera" and I have no indication that the source dictionary is under an open license.

Unless you can prove me wrong, I wont add it. Sorry.

**Comment by d0b3rm4n** [comment]
source dictionary seems not to be under an open license
